import geoalchemy2
"""empty message

Revision ID: 36ccccd888ee
Revises: aa22a3bcac3b
Create Date: 2020-01-23 13:45:29.566806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ccccd888ee'
down_revision = 'aa22a3bcac3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_tv_command_sensor_data', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_tv_command_sensor_data', sa.Column('status', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
